# Generated by Django 4.2.3 on 2023-07-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('pinyin', models.CharField(max_length=10)),
                ('public_classify_dataset', models.CharField(max_length=100, verbose_name='公共分类数据')),
                ('public_score_dataset', models.CharField(max_length=100, verbose_name='公共评分数据')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('pinyin', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('last_time', models.DateField(null=True, verbose_name='最新时间')),
                ('medical_history', models.CharField(max_length=2000, verbose_name='病例')),
                ('training_plan', models.CharField(max_length=2000, verbose_name='训练计划')),
                ('training_result', models.CharField(max_length=2000, verbose_name='训练结果')),
                ('classify_dataset', models.CharField(max_length=100, verbose_name='分类数据')),
                ('classify_model', models.CharField(max_length=100, verbose_name='分类模型')),
                ('score_dataset', models.CharField(max_length=100, verbose_name='评分数据')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.doctor', verbose_name='外键')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
