# Generated by Django 4.2.3 on 2023-07-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_doctor_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='public_classify_dataset',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='public_score_dataset',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_time',
        ),
    ]
